#ifndef FUNMODULEINTERFACE_GLOBAL_H
#define FUNMODULEINTERFACE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FUNMODULEINTERFACE_LIBRARY)
#  define FUNMODULEINTERFACESHARED_EXPORT Q_DECL_EXPORT
#else
#  define FUNMODULEINTERFACESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // FUNMODULEINTERFACE_GLOBAL_H
