#ifndef COWIDGETBOX_GLOBAL_H
#define COWIDGETBOX_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COWIDGETBOX_LIBRARY)
#  define COWIDGETBOXSHARED_EXPORT Q_DECL_EXPORT
#else
#  define COWIDGETBOXSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // COWIDGETBOX_GLOBAL_H
