#ifndef HARDWAREFROM_GLOBAL_H
#define HARDWAREFROM_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(HARDWAREFROM_LIBRARY)
#  define HARDWAREFROMSHARED_EXPORT Q_DECL_EXPORT
#else
#  define HARDWAREFROMSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // HARDWAREFROM_GLOBAL_H
