#ifndef DATAMANAGERPERMISS_GLOBAL_H
#define DATAMANAGERPERMISS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DATAMANAGERPERMISS__LIBRARY)
#  define DATAMANAGERPERMISSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DATAMANAGERPERMISSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DATABASEPERMISS__GLOBAL_H

