#ifndef LOADFILEMANAGER_GLOBAL_H
#define LOADFILEMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LOADFILEMANAGER_LIBRARY)
#  define LOADFILEMANAGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LOADFILEMANAGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LOADFILEMANAGER_GLOBAL_H
