#ifndef COGRAPHICSITEMS_GLOBAL_H
#define COGRAPHICSITEMS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COGRAPHICSITEMS_LIBRARY)
#  define COGRAPHICSITEMSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define COGRAPHICSITEMSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // COGRAPHICSITEMS_GLOBAL_H
