#ifndef TORQUECHART_GLOBAL_H
#define TORQUECHART_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TORQUECHART_LIBRARY)
#  define TORQUECHARTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TORQUECHARTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TORQUECHART_GLOBAL_H
