#ifndef MULTHREACOPYFILE_GLOBAL_H
#define MULTHREACOPYFILE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MULTHREACOPYFILE_LIBRARY)
#  define MULTHREACOPYFILESHARED_EXPORT Q_DECL_EXPORT
#else
#  define MULTHREACOPYFILESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MULTHREACOPYFILE_GLOBAL_H
