#ifndef MQTTMANAGER_GLOBAL_H
#define MQTTMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MQTTMANAGER_LIBRARY)
#  define MQTTMANAGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MQTTMANAGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MQTTMANAGER_GLOBAL_H
