#ifndef SECRETMANAGER_GLOBAL_H
#define SECRETMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SECRETMANAGER_LIBRARY)
#  define SECRETMANAGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SECRETMANAGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SECRETMANAGER_GLOBAL_H
