#ifndef EVENTMANAGER_GLOBAL_H
#define EVENTMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(EVENTMANAGER_LIBRARY)
#  define EVENTMANAGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define EVENTMANAGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // EVENTMANAGER_GLOBAL_H
