#ifndef DATAMANAGERFORM_GLOBAL_H
#define DATAMANAGERFORM_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DATAMANAGERFORM_LIBRARY)
#  define DATAMANAGERFORMSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DATAMANAGERFORMSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DATAMANAGERFORM_GLOBAL_H
